services:
  - name: auditpro-backend
    type: web
    env: node
    plan: free
    rootDir: .
    autoDeploy: true
    nodeVersion: 18
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: ""
      - key: PYTHON_SERVICE_URL
        value: ""
      - key: CLIENT_URL
        value: ""

# Notes:
# - Switch from Docker to native Node environment to ensure devDependencies (types) install.
# - Fill in MONGODB_URI, PYTHON_SERVICE_URL, CLIENT_URL via Render dashboard (mark secrets where needed).